# Generated by Django 2.0.3 on 2018-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='DockerMarket/dockers')),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=75)),
                ('unique_id', models.CharField(max_length=100)),
                ('keys', models.ManyToManyField(blank=True, to='DockerMarket.Key')),
            ],
        ),
        migrations.AddField(
            model_name='docker',
            name='developer',
            field=models.ForeignKey(on_delete='CASCADE', to='DockerMarket.User'),
        ),
    ]
